site_name: School of DevOps
site_description: School of DevOps Doc
site_url: https://moabukar.github.io/school-of-devops/
site_author: Mohamed Abukar

repo_url: https://github.com/moabukar/school-of-devops
dev_addr: "127.0.0.1:8000"
docs_dir: docs
theme: 
  name: dracula
  # custom_dir: overrides
  extra_css:
    - stylesheets/custom.css

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  i18n:
    prev: 'Previous'
    next: 'Next'

plugins:
  - search
  # - exclude:
  #     glob:
  #       - "**/include-*.md"
  - git-revision-date
  # - pdf-export:
  #     combined: true

nav:
- Home: index.md
- Level 1 (Fundamentals) :
    - Linux:
        - Basics: level1/linux/basics.md
        - CLI: level1/linux/cli.md
    - Git:
        - Basics: level1/git/git-basics.md
        - Working With Branches: level1/git/branches.md
        - Github and Hooks: level1/git/github-hooks.md
        - Conclusion: level1/git/conclusion.md
    - Networking:
        - Syllabus: level1/networking/plan.md
        - OSI Model: level1/networking/osi.md
        - Basics: level1/networking/basics.md
        - Protocols: level1/networking/protocols.md
        - Proxies: level1/networking/proxies.md
        - Load balancers: level1/networking/load-balancers.md
    - AWS:
        - Syllabus: level1/aws/plan.md
        - Introduction: level1/aws/intro.md
        - Compute: level1/aws/compute.md


- Level 2 (Infrastructure & Containers):
    - Terraform:
        - Syllabus: level2/terraform/plan.md
        - Intro: level2/terraform/intro.md
        - Basics: level2/terraform/basics.md
        - Building with Terraform: level2/terraform/building.md
        - Modules & Advanced: level2/terraform/modules.md
        - Terraform in the Cloud: level2/terraform/cloud.md
        - Best Practices: level2/terraform/best-practices.md
    - Docker:
        - Syllabus: level2/docker/plan.md
        - Intro: level2/docker/intro.md
        - Basics: level2/docker/basics.md
        - Containers: level2/docker/containers.md
        - Building with Docker: level2/docker/building.md
        - Docker Compose & Multi-Container Apps: level2/docker/compose.md
        - Advanced & Best Practices: level2/docker/advanced.md
    - CICD:
        - Syllabus: level2/cicd/plan.md
        - Intro to CICD: level2/cicd/intro.md
        - Getting started with GitHub Actions: level2/cicd/basics.md
        - Continuous Integration with GitHub Actions: level2/cicd/ci.md
        - Continuous Deployment & Delivery with GitHub Actions: level2/cicd/cd.md
        - IaC & GitHub Actions: level2/cicd/iac.md
        - Advanced Features: level2/cicd/advanced.md
        - Real-world applications: level2/cicd/real-world.md
    - Kubernetes:
        - Syllabus: level2/k8s/plan.md
        - Basics: level2/k8s/intro.md
        - Setting up a K8s environemnt: level2/k8s/setup.md
        - K8s core concepts: level2/k8s/basics.md
        

- Level 3 (Scripting & Coding):
    - Python:
        - Python plan: level3/python/basics.md
    - Golang:
        - Golang basics: level3/golang/basics.md
    - Scripting:
        - Scripting basics: level3/scripting/basics.md

- Level 4 (Monitoring & Infra Management):
    - Ansible:
        - Ansible plan: level4/ansible/basics.md
    - Helm:
        - Helm basics: level4/helm/basics.md
    - Monitoring:
        - Monitoring basics: level4/monitoring/basics.md
    - SRE:
        - SRE basics: level4/sre/basics.md

- Contribute: CONTRIBUTING.md
- Code of Conduct: CODE_OF_CONDUCT.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  

copyright: |
  &copy; 2023 <a href="https://github.com/moabukar"  target="_blank" rel="noopener">Mohamed Abukar</a>

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/moabukar
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/moabukar_1
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/moabukar/
